allergies/urls.py
from django.urls import path, re_path

from . import views

app_name = 'allergies'
urlpatterns = [
    path('', views.search, name='index'),
    path('request/', views.ask, name='request'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('get_names/', views.get_restaurant, name='get_names'),
]

allergy_website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('allergies.urls')),
    path('admin/', admin.site.urls),
]

allergies/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Link(models.Model):
    restaurant_name = models.CharField(max_length=200)
    rest_link = models.CharField(max_length=200)
    add_date = models.DateTimeField('date added')

    def __str__(self):
        return self.restaurant_name


class Request(models.Model):
    request_name = models.CharField(max_length=200)
    request_link = models.CharField(max_length=200, blank=True, default='None provided')
    request_date = models.DateTimeField('date requested', blank=True, default=timezone.now)

    def __str__(self):
        return self.request_name

    def was_requested_recently(self):
        return self.request_date >= timezone.now() - datetime.timedelta(days=1)

allergies/forms.py
from django import forms
from allergies.models import Request

class RequestForm(forms.ModelForm):
    """Form for user to add request"""
    request_name = forms.CharField(
        max_length=200,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter restaurant name here', 'autofocus': ''})
    )
    request_link = forms.CharField(
        required=False,
        max_length=200,
        widget=forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'Enter link to allergy guide here (optional)'})
    )
    class Meta:
        model = Request
        fields = ['request_name', 'request_link']


class ContactForm(forms.Form):
    from_email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter your email address', 'autofocus': ''})
    )
    subject = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Subject of your message'})
    )
    message = forms.CharField(
        required=True,
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Type your message here'})
    )

allergies/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.utils import timezone
from django.core.serializers.json import DjangoJSONEncoder
import json
import requests
from django.contrib import messages
from django.core.mail import send_mail, BadHeaderError
from django.conf import settings
from functools import wraps

from .models import Link, Request
from .forms import RequestForm, ContactForm

def check_recaptcha(view_func):
    """Decorator for reCAPTCHA validation"""
    @wraps(view_func)
    def _wrapped_view(request, *args, **kwargs):
        request.recaptcha_is_valid = None
        if request.method == "POST":
            recaptcha_response = request.POST.get('g-recaptcha-response')
            data = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
            result = r.json()

            if result['success']:
                request.recaptcha_is_valid = True
            else:
                request.recaptcha_is_valid = False
                messages.error(request, "Invalid reCAPTCHA. Please try again.")
        return view_func(request, *args, **kwargs)
    return _wrapped_view


# Create your views here.
def index(request):
    """Loads the home page for allergies app"""
    return render(request, 'allergies/index.html')


def search(request):
    """Loads the search page for the allergies app"""
    rest_list = Link.objects.order_by('restaurant_name')
    context = {'rest_list': rest_list}
    return render(request, 'allergies/search.html', context)


@check_recaptcha
def ask(request):
    """Loads the request page for the allergies app if GET, writes request to
       database if successful POST"""
    
    if request.method == 'POST':
        form = RequestForm(request.POST)
        if form.is_valid() and request.recaptcha_is_valid:
            request_name = form.cleaned_data.get('request_name')
            check_name = request_name
            if Link.objects.filter(restaurant_name__iexact=check_name).exists():
                messages.error(request, "Info for that restaurant has already been entered.")
                return HttpResponseRedirect(reverse('allergies:request'))
            elif Request.objects.filter(request_name__iexact=check_name).exists():
                messages.error(request, "Info for that restaurant has already been requested.")
                return HttpResponseRedirect(reverse('allergies:request'))
            req = form.save(commit=False)
            req.request_date = timezone.now()
            req.save()
            messages.success(request, "Your request has been successfully processed.")
            subject = "New request received: " + request_name
            body = "New allergen information requested for " + request_name
            status = send_message(subject, 'autorequest@allergysite.com', body)
        return HttpResponseRedirect(reverse('allergies:request'))

    elif request.method == 'GET':
        form = RequestForm()
        context = {'form': form}
        return render(request, 'allergies/request.html', context)


def get_restaurant(request):
    """Looks up restaurant names similar to the user's query"""
    if request.is_ajax():
        q = request.GET.get('term', '')
        queryset = Link.objects.filter(restaurant_name__icontains=q).order_by('restaurant_name')
        results = [{'label': item.restaurant_name, 'value': item.rest_link} for item in queryset]
        data = json.dumps(list(results), cls=DjangoJSONEncoder)
    else:
        data = 'fail'

    return HttpResponse(data, content_type='application/json')


@check_recaptcha
def contact(request):
    """Loads the contact page for the allergies app"""
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid() and request.recaptcha_is_valid:
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            messages.success(request, "Your email has been sent.")
            try:
                send_mail(subject, message, from_email, ['allergy.list.website@gmail.com'])
            except BadHeaderError:
                return HttpResponse("Invalid email header information")
            return HttpResponseRedirect(reverse('allergies:contact'))
        else:
            form = ContactForm()
    return render(request, "allergies/email.html", {'form': form})


def about(request):
    """Loads the about page for allergies app"""
    return render(request, 'allergies/index.html')


def send_message(subject, from_email, message):
    """
    Sends email to website account.

    subject is a string with the message subject
    from_email is the from address for the message
    message is the message body
    """
    try:
        send_mail(subject, message, from_email, ['allergy.list.website@gmail.com'])
        return True
    except BadHeaderError:
        print("Error sending email")
        return False

allergies/templates/allergies/email.html
{% extends "allergies/layout.html" %}

{% block title %}
    Contact
{% endblock %}

{% block main %}
<div class="container-fluid">
<h1>Contact Me</h1>
<p>If you have any questions or concerns, would like to see a feature added to the website, 
    or would like me to remove one of the allergy lists I have posted, use this form to contact me. Please provide
    a valid email address so that I can respond if I have follow-up questions.
</p>

{% if messages %}
<div class="notification">
    {% for message in messages %}
    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
    {% endfor %}
</div>
{% endif %}

<div style="width:100%">
    <form id="contact" method="POST">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        {{field}}
    </div>
    {% endfor %}
    <script src='https://www.google.com/recaptcha/api.js'></script>
    <div class="g-recaptcha" data-sitekey="6Len51gUAAAAAO84UpoOdQ6yAnUS7QOW4bL_Kip1" data-callback="recaptcha_callback_email"></div>
    <input class="btn btn-primary mt-2" type="submit" id="email_submit" value="Send message" disabled>
    </form>
</div>
</div>
{% endblock %}

allergies/templates/allergies/index.html
{% extends "allergies/layout.html" %}

{% block title %}
    Home
{% endblock %}

{% block main %}
<div class="row">
    <h1>Compiled Allergen Information</h1>
    <p>
        Thank you for visiting my website! To give you a little background, I'm extremely lactose intolerant (as is my wife),
        and I was recently informed that I have a peanut allergy (though it's not life threatening). As you can imagine, eating out
        is not as easy for me and my wife as it is for many other people, since we're always concerned that we may eat something that
        disagrees with us and makes the entire experience highly unpleasant. I've discovered that many chain restaurants (and some
        smaller ones) post allergen guides on their websites. While this is extremely helpful, they're often difficult to find. Since
        I'm sure there are others out there who would like easier access to this sort of information, I've decided to keep a compiled
        list of where to find various restaurants' allergen guides. Please feel free to browse at your leisure, and I hope you find this
        website useful!
    </p>
</div>
<div class="row">
    <h2>Instructions</h2>
    <p>
        Use the bar above to navigate this website. If you'd like to view the allergen guides that I've catalogued so far, use the search
        functionality on the home page. There, you can either type the name of a restaurant to see if I have entered its information,
        or select an option from a drop-down list. If you would instead like to request that I enter the information for another
        restaurant, click "request" and fill out the form. Finally, if you would like to contact me (whether to request that I add a
        feature to the website, to make a recommendation to improve the user experience, to request that I take down a listing,
        or simply to tell me what a great job I'm doing), simply click "contact" above and send me a message. Thank you!
    </p>
</div>
<div class="row">
<h4>Disclaimers</h4>
    <ul>
        <li>
            Because I do not work for any of these restaurants, and because I've never been to many of them, I am
            unable to verify the accuracy of these allergen guides. If you have a food intolerance or allergy (especially a life-threatening
            one), please do your own research and ask for further information from the restaurants themselves.
        </li>
        <li>
            I do not claim ownership or copyright of any material drawn from other companies' websites. If for any reason you
            or your company would like me to take down a link to your allergen guide, please contact me via the "contact" page.
        </li>
    </ul>
</div>
{% endblock %}

allergies/templates/allergies/layout.html
<!DOCTYPE html>

<html lang="en">

    <head>

        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- get bootstrap and jquery ui stylesheets -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <!-- get local stylesheet -->
        {% load static %}
        <link href="{% static 'allergies/styles.css' %}" rel="stylesheet"/>
        <!-- get favicon -->
        <link rel="icon" type="image/x-icon" href="{% static 'allergies/favicon.ico' %}">
        <!-- get touch icon -->
        <link rel="apple-touch-icon-precomposed" href="{% static 'allergies/rod-of-asclepius-152-211396.png' %}">
        <!-- jquery and jquery ui -->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
        <!-- local js -->
        <script src="{% static 'allergies/scripts.js' %}"></script>
        {% block header %}{% endblock %}
        <title>Allergy Information: {% block title %}{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark sticky-top bg-dark">
            <a class="navbar-brand" href="{% url 'allergies:index' %}">Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <ul class="navbar-nav mr-auto mt-2">
                    <li class="nav-item"><a class="nav-link" href="{% url 'allergies:request' %}">Request</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'allergies:contact' %}">Contact</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'allergies:about' %}">About</a></li>
                </ul>
            </div>
        </nav>

        <main role="main" class="container p-4">
            {% block main %}{% endblock %}
        </main>

        {% block footer %}{% endblock %}
    </body>
</html>

allergies/templates/allergies/request.html
{% extends "allergies/layout.html" %}

{% block title %}
    Request
{% endblock %}

{% block main %}
<div class="container-fluid">
<h1>Submit a Request</h1>
<p>
    Here you may request that I add another restaurant's allergy information to this website. I ask that you please look for it
    first on the "search" page to ensure that I haven't already uploaded it. In addition, if you already know the link to the website,
    I ask that you send that in the provided box as well (though this is not required). Thank you for helping to build this
    project!
</p>

{% if messages %}
<div class="notification">
    {% for message in messages %}
    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
    {% endfor %}
</div>
{% endif %}

<div style="width:100%">
    <form id="request" method="POST">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        {{field}}
    </div>
    {% endfor %}
    <script src='https://www.google.com/recaptcha/api.js'></script>
    <div class="g-recaptcha" data-sitekey="6Len51gUAAAAAO84UpoOdQ6yAnUS7QOW4bL_Kip1" data-callback="recaptcha_callback_request"></div>
    <input class="btn btn-primary mt-2" type="submit" id="request_submit" value="Submit Request" disabled>
    </form>
</div>
{% endblock %}

allergies/templates/allergies/search.html
{% extends "allergies/layout.html" %}

{% block title %}
    Search
{% endblock %}

{% block main %}
        <h1>Search</h1>
        <p>You may either select a restaurant from the drop-down list or use the search box below. I do my best to keep
            this information up-to-date, but if a link is broken or outdated please report it to me. Each restaurant 
            provides its allergen information differently (some via pdf, some directly in their menu, etc.), so I try
            to provide the link that will be most immediately useful.
        </p>
        <p style="font-size: 14px; color: red;"><em>Disclaimer: I cannot verify the accuracy of these allergen guides. Please supplement this information with
            your own research and use your own best judgment.
        </em></p>
        {% if rest_list %}
        <form id="dd">
        {% csrf_token %}
            <div class="form-group">
                <select class="form-control" name="restaurant" id="rstrnt">
                    <option value="" selected>Select a restaurant:</option>
                    {% for rest in rest_list %}
                        <option value="{{ rest.rest_link }}">{{ rest.restaurant_name }}</option>
                    {% endfor %}
                </select>
            </div>
        </form>
        {% else %}
            <p>No information currently available</p>
        {% endif %}
        <form id="form" class="mt-4">
            {% csrf_token %}
            <div class="form-group">
                <label for="q">Enter restaurant yourself:&nbsp;</label>
                <br>
                <input type="text" class="form-control" id="q" autofocus autocomplete="off" placeholder="Type restaurant name">
            </div>
        </form>
        <div id="pdf-div" style="display: none;">
            <object id="pdf-viewer" data="" type="application/pdf" width="100%" height="500px">
                <param name="view" value="FitH"/>
                <p>Your browser doesn't support embedded PDFs. You can <a id="alt_pdf_link" href="">download the PDF here</a>.</p>
            </object>
        </div>
{% endblock %}
{% block footer %}
<script>
    $(function() {
        $("#q").autocomplete({
            source: "{% url 'allergies:get_names' %}",
            minLength: 3,
            autoFocus: true,
            focus: function(event, ui) {
                return false;
            },
            select: function(event, ui) {
                var link = ui.item.value;
                $("#q").val(ui.item.label);
                if (link.includes(".pdf")) {
                    $("#pdf-viewer").attr("data", link + "?#view=FitH");
                    $("#alt_pdf_link").attr("href", link);
                    $("#pdf-div").show();
                }
                else {
                    $("#pdf-div").hide();
                    var win = window.open(link, '_blank');
                    win.focus();
                }
                return false;
            },
        });
    });
</script>
{% endblock %}